elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /c/Users/docker/elasticsearch-data:/usr/share/elasticsearch/data

logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - /c/Users/docker/logstash-config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - /c/Users/docker/kibana-config:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
