server:
  port: 8761

eureka: 
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_INSTANCE_IPADDRESS}
    nonSecurePort: 8761

logging:
  level:
    root: WARN
