server:
  port: 0

spring:
  application:
    name: simple-client
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_INSTANCE_IPADDRESS}:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}      

---
spring:
  profiles: docker
eureka:
  instance:
     preferIpAddress: true
     ipAddress: ${EUREKA_INSTANCE_IPADDRESS}