server:
  port: 0

spring:
  application:
    name: simple-client
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.101:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
---
spring:
  profiles: docker
eureka:
  instance:
     preferIpAddress: true
     ipAddress: ${EUREKA_INSTANCE_IPADDRESS}